name: Dependency Review

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-review:
    uses: chargehound/security-workflows/.github/workflows/dependency-review.yml@main